### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by AlokGupta007** [akofman/cordova-plugin-permissionScope#4]
Hi I am unable to add plugin.

Here is the error with install command.
internet is good so no issue regards internet

algupta$ **ionic cordova plugin add cordova-plugin-permissionScope --save**
> cordova plugin add cordova-plugin-permissionScope --save
(node:2261) UnhandledPromiseRejectionWarning: CordovaError: Failed to fetch plugin cordova-plugin-permissionScope via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 1 Error output:
sh: babel: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! cordova-plugin-permissionScope@2.1.1 build: `babel src/www -d .`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the cordova-plugin-permissionScope@2.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/algupta/.npm/_logs/2018-06-21T06_48_23_313Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cordova-plugin-permissionScope@2.1.1 install: `npm run build && cd tests/app && cordova platform rm ios && cordova platform add ios`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cordova-plugin-permissionScope@2.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/algupta/.npm/_logs/2018-06-21T06_48_24_015Z-debug.log
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/fetch.js:173:37
    at _rejected (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:864:24)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:890:30
    at Promise.when (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:808:41)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:624:44
    at runSingle (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:112:11)
(node:2261) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without acatch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2261) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bctan73** [comment]
Any solution for this? I got the same error not able to install this plug in
